version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: backend-app
    volumes:
      - ./:/var/www/html
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - appnet

  web:
    image: nginx:stable
    container_name: backend-web
    ports:
      - "8080:80"   # http://localhost:8080
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - appnet

  db:
    image: postgres:16
    container_name: backend-db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - appnet

volumes:
  dbdata:

networks:
  appnet:
    driver: bridge
